<?php
/*====================================================
*   Copyright (C) 2014 All rights reserved.
*
*   Filename      : common.inc
*   Author        : dongjiang.dongj@alibaba-inc.com
*   Last modified : 2014-11-22 16:34
*   Description : 
======================================================*/
declare(encoding='UTF-8');
namespace common;
/**
* 定义基础常量. 如 mysql的常量；超时时间等
*/
$DBServer = array(
    array(
        'ip' => "10.232.31.166",
        'port' => 3506,
        'user' => "kgb",
        'password' => "kgb",
    ),
    array(
        'ip' => "10.232.31.166",
        'port' => 3506,
        'user' => "kgb",
        'password' => "kgb",
    ),
};
?>
